BookStore_project/Controllers/AuthorController.cs
using BookStore_project.Models.Author;
using Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PagedList;
using Service;
using Service.implementation;
using Service.Implementation;

namespace BookStore_project.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorService _authorService;
        private ICategoryService _categoryService;
        private IBookService _bookService;
        private IWebHostEnvironment _hostingEnvironment;
        public AuthorController(IAuthorService authorService, IBookService bookService, ICategoryService categoryService, IWebHostEnvironment hostingEnvironment)
        {
            _authorService = authorService;
            _bookService = bookService;
            _categoryService = categoryService;
            _hostingEnvironment = hostingEnvironment;
        }
        
        public IActionResult Index(int? page)
        {
             if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            var model = _authorService.GetAll().Select(Author => new AuthorIndexViewModel
            {
                ID = Author.ID,
                Name = Author.Name,
                DOB = Author.DOB,
                img_url = Author.img_url
            }).OrderBy(x=>x.ID).ToList();
            int pagesize = 5;
            int pagenumber = (page ?? 1);

            return View(model.ToPagedList(pagenumber,pagesize));
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var author = _authorService.GetById(id);
            var author_book = _authorService.getBookByAuthorID(id);
            var model = new AuthorDetailViewModel();
            model.ID = author.ID;
            model.Name = author.Name;
            model.DOB = author.DOB;
            model.Img_url = author.img_url;
            model.lob = author_book;
            foreach(var items in model.lob)
            {
                var cate = _categoryService.GetByID(items.CategoryID);
                items.Category = cate;
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var author = _authorService.GetById(id);
            var model = new AuthorDeleteViewModel();
            model.ID = author.ID;
            model.Name = author.Name;
            model.DOB = author.DOB;
            model.img_url = author.img_url;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(AuthorDeleteViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var author = _authorService.GetById(model.ID);
                await _authorService.DeleteAsSync(author);
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            var model = new AuthorCreateViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuthorCreateViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var author = new Author
                {
                    ID = model.ID,
                    Name = model.Name,
                    DOB = model.DOB

                };
                if (model.Image_URL != null && model.Image_URL.Length > 0)
                {
                    var uploadDir = @"img/authors";
                    var fileName = Path.GetFileNameWithoutExtension(model.Image_URL.FileName);
                    var extension = Path.GetExtension(model.Image_URL.FileName);
                    var webrootPath = _hostingEnvironment.WebRootPath;
                    fileName = DateTime.UtcNow.ToString("yymmssfff") + fileName + extension;
                    var path = Path.Combine(webrootPath, uploadDir, fileName);
                    await model.Image_URL.CopyToAsync(new FileStream(path, FileMode.Create));
                    author.img_url= "/" + uploadDir + "/" + fileName;
                }
                await _authorService.CreateAsSync(author);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var author = _authorService.GetById(id);
            var model = new AuthorEditViewModel();
            model.ID = author.ID;
            model.Name = author.Name;
            model.DOB = author.DOB;
            model.Img_url = author.img_url;

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AuthorEditViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var author = new Author
                {
                    ID = model.ID,
                    Name = model.Name,
                    DOB = model.DOB,
                    img_url = model.Img_url
                };
                await _authorService.UpdateAsSync(author);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult SearchPage()
        {
            var model = new AuthorSearchViewModel();
            return View(model);
        }
        public IActionResult SearchByAuthorName(string name)
        {
            var model = _authorService.getAuthorbyName(name).Select(Author => new AuthorIndexViewModel
            {
                ID = Author.ID,
                Name = Author.Name,
                DOB = Author.DOB,
                img_url = Author.img_url
            }).ToList();
            return View(model);

        }
    }
}

BookStore_project/Controllers/BillController.cs
using BookStore_project.Models.Bill;
using Entity;
using Service;
using Microsoft.AspNetCore.Mvc;
using Service.Implementation;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;
using PagedList;
using Microsoft.AspNetCore.Identity;

namespace BookStore_project.Controllers {

    [Authorize(Roles = "Admin")]

    public class BillController : Controller {
        private IBillService _billService;
        private IStatusService _StatusService;
        private IShipmentService _shipmentservice;
        private readonly UserManager<IdentityUser> _userManager;

        public BillController(IBillService billService, IStatusService StatusService, IShipmentService Shipmentservice, UserManager<IdentityUser> UserManager)
        {
            _userManager = UserManager;

            _shipmentservice = Shipmentservice;
            _StatusService = StatusService;
            _billService = billService;
        }
        public async Task<IActionResult> CustomerDetailAsync(string name)
        {
            var user = await _userManager.FindByNameAsync(name) as IdentityUser;
            var list = _billService.FindBillByUser(user.Id);
            var model = new CustomerBillDetailViewModel();
            model.Id = user.Id;
            model.Name = user.UserName;
            model.Phone = user.PhoneNumber;
            model.Email = user.Email;
            return View(model);
        }
        public IActionResult Index(int ? page){
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            var model = _billService.GetAll().Select( Bill => new BillIndexViewModel
            {
                ID = Bill.ID,
                Date = Bill.Date,
                Total_money = Bill.Total_money,
                Customer_ID = Bill.Customer_ID,
                Employee_ID = Bill.Employee_ID,
                Bill_status_ID = _StatusService.GetByID(Bill.Bill_status_ID).Name
            }).OrderBy(x=>x.ID).ToList();
            int pagesize = 5;
            int pagenumber = (page ?? 1);

            return View(model.ToPagedList(pagenumber, pagesize));

        }
        [HttpGet]
        
        public IActionResult Detail(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var bill = _billService.GetByID(id);
            var model = new BillDetailViewModel();
            model.ID = bill.ID;
            model.Date = bill.Date;
            model.Total_money = bill.Total_money;
            model.Customer_ID = bill.Customer_ID;
            model.Employee_ID = bill.Employee_ID;
            model.Bill_status_ID = bill.Bill_status_ID;
            var listdetail = _billService.GetBillDetailByBill(id);
            model.ListOfBillDetail = listdetail;
            return View(model);
        }
        [HttpGet]
       
        public IActionResult Delete(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var bill = _billService.GetByID(id);
            var model = new BillDeleteViewModel();
            model.ID = bill.ID;
            model.Date = bill.Date;
            model.Total_money = bill.Total_money;
            model.Customer_ID = bill.Customer_ID;
            model.Employee_ID = bill.Employee_ID;
            model.Bill_status_ID = bill.Bill_status_ID;
            return View(model);
        }
        [HttpGet]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Delete(BillDeleteViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var bill = _billService.GetByID(model.ID);
                await _billService.DeleteAsSync(bill);
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
       
        public IActionResult Create()
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            var model = new BillCreateViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Create(BillCreateViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var bill = new Bill
                {
                    ID = model.ID,
                    Date = model.Date,
                    Total_money = model.Total_money,
                    Customer_ID = model.Customer_ID,
                    Employee_ID = model.Employee_ID,
                    Bill_status_ID = model.Bill_status_ID

                };
                await _billService.CreateAsSync(bill);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
       
        public IActionResult Edit(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var bill = _billService.GetByID(id);
            var model = new BillDeleteViewModel();
            model.ID = bill.ID;
            model.Date = bill.Date;
            model.Total_money = bill.Total_money;
            model.Customer_ID = bill.Customer_ID;
            model.Employee_ID = bill.Employee_ID;
            model.Bill_status_ID = bill.Bill_status_ID;

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Edit(BillEditViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var bill = new Bill
                {
                    ID = model.ID,
                    Date = model.Date,
                    Total_money = model.Total_money,
                    Customer_ID = model.Customer_ID,
                    Employee_ID = model.Employee_ID,
                    Bill_status_ID = model.Bill_status_ID
                };
                await _billService.UpdateAsSync(bill);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
       
        public IActionResult Process(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var bill = _billService.GetByID(id);
            var model = new BillProcessViewModel();
            var user = _billService.FindBillByUser(bill.Customer_ID);
            model.Date = bill.Date;
            model.Total = bill.Total_money;
            var statusName = _StatusService.GetByID(bill.Bill_status_ID).Name.ToString();
            model.status = statusName;
            if (statusName.Equals("Canceled") || bill.Bill_status_ID==3)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Process(BillProcessViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var bill = _billService.GetByID(model.id);
                bill.Bill_status_ID++;
                await _billService.UpdateAsSync(bill);
                if (bill.Bill_status_ID == 2)
                {
                    var ship = new Shipment();
                    ship.BillID = bill.ID;
                    ship.Shipment_Status_ID = 2;
                    var user = await _userManager.FindByNameAsync(bill.Customer_ID) as IdentityUser;
                    ship.CustomerName = user.UserName;
                    ship.CustomerID = user.Id;
                    await _shipmentservice.CreateAsAsync(ship);
                   
                }
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
        
        public IActionResult Canceled(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id.ToString() == null)
            {
                return NotFound();
            }
            var bill = _billService.GetByID(id);
            var model = new BillCanceledViewModel();
            var user = _billService.FindBillByUser(bill.Customer_ID);
            model.Date = bill.Date;
            model.Total = bill.Total_money;
            var statusName = _StatusService.GetByID(bill.Bill_status_ID).Name.ToString();
            model.status = statusName;
           if (statusName.Equals("Canceled") || statusName.Equals("Shipped"))
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]

BookStore_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/BookStore_project.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" asp-append-version="true" />
    <link href="~/css/layoutUser.css" rel="stylesheet" />
    <style>
        .dropdown:hover .dropdown-menu{
            display: block;
        }
        .navbar-nav {
            background-color: #cc4125;
        }

        .navbar-nav.two {
            background-color: #fff;
        }
        .navbar-nav .nav-item .nav-link{
            color: #fff;
            font-size: 18px;
            font-weight: 600;
            margin-right: 15px;
        }

        .navbar-nav .nav-item:hover .nav-link{
            color: #81d8d0 ;
            transition: 0.3s;
        }

        .container-fluid {
            flex-direction: column;
            margin-bottom: 20px;
        }
        
        .container-fluid .row-one {
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            align-items: center;
            width: 100%;
        }

        .container-fluid .row.two {
            width: 90%;
            margin-top:20px;
        }
    </style>
</head>
<body>
        <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div class="row-one">
                     <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img style="width: 250px" src="~/img/books/Logo.png" />
                     </a>
                     <div class="col-4 p-0 justify-content-end">
                        <form asp-action="Index" asp-controller="Home">
                            <div class="form-group">
                                <input class="form-control" type="text" name="SearchText" placeholder="Search Key">
                                <input class="btn btn-primary" type="submit" value="Search">
                            </div>
                        </form>
                    </div>
                    <partial name="_LoginPartial" />
                </div>

                <div class="row two">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    CRM management
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Employee" asp-action="Index">Employee</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Publisher" asp-action="Index">Publisher</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Author" asp-action="Index" asp-route-page="1">Author</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Export-Import
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Bill" asp-action="Index">Bill</a></li>
                                    <li><a class="dropdown-item" asp-controller="Import" asp-action="Index">Import</a></li>
                                    <li><a class="dropdown-item" asp-controller="Shipment" asp-action="Index">Shipment</a></li>

                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="BillDetail" asp-action="Index">Bill Detail</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                        </ul>
                        
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
            @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Book Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStore_project/Views/Shared/_layoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore_project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" asp-append-version="true" />
    <link href="~/css/layoutUser.css" rel="stylesheet" />

    @*
    <style>
        .dropdown:hover .dropdown-menu {
            display: block;
        }

        .navbar-nav {
            background-color: #cc4125;
        }

            .navbar-nav.two {
                background-color: #fff;
            }

            .navbar-nav .nav-item .nav-link {
                color: #fff;
                font-size: 18px;
                font-weight: 600;
                margin-right: 15px;
            }

            .navbar-nav .nav-item:hover .nav-link {
                color: #81d8d0;
                transition: 0.3s;
            }

        .container-fluid {
            flex-direction: column;
            margin-bottom: 20px;
        }

            .container-fluid .row-one {
                display: flex;
                flex-direction: row;
                justify-content: space-around;
                align-items: center;
                width: 100%;
            }

            .container-fluid .row.two {
                width: 90%;
                margin-top: 20px;
            }
    </style>

    *@
</head>
<body>

    @*

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div class="row-one">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img style="width: 250px" src="~/img/books/Logo.png" />
                    </a>
                    <div class="col-4 p-0 justify-content-end">
                        <form asp-action="Index" asp-controller="Home">
                            <div class="form-group">
                                <input class="form-control" type="text" name="SearchText" placeholder="Search Key">
                                <input class="btn btn-primary" type="submit" value="Search">
                            </div>
                        </form>
                    </div>
                    <partial name="_LoginPartial" />
                </div>

                <div class="row two">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    CRM management
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Employee" asp-action="Index">Employee</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Publisher" asp-action="Index">Publisher</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Author" asp-action="Index" asp-route-page="1">Author</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Export-Import
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Bill" asp-action="Index">Bill</a></li>
                                    <li><a class="dropdown-item" asp-controller="Import" asp-action="Index">Import</a></li>
                                    <li><a class="dropdown-item" asp-controller="Shipment" asp-action="Index">Shipment</a></li>

                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="BillDetail" asp-action="Index">Bill Detail</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </nav>
    </header>
    *@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width: 250px" src="~/img/books/Logo.png" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
            @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>